CREATE TABLE IF NOT EXISTS public.groups
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    levelnum integer NOT NULL,
    ordernum integer NOT NULL,
    parentnode integer,
    rootnode integer,
    txtgroup character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT groups_pkey PRIMARY KEY (id),
    CONSTRAINT uk9uejlgx2wy4i4j7puypy62nmp UNIQUE (rootnode, ordernum),
    CONSTRAINT uk9uodqy7h6mmbb48q33kpfgdsi UNIQUE (parentnode, txtgroup)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.groups
    OWNER to postgres;

CREATE INDEX IF NOT EXISTS idx1t27gtrqkafdiinysvptt7rby
    ON public.groups USING btree
    (txtgroup COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
